### ISSUE TITLE
Doesn't work with vscode 1.20

### ISSUE THREAD

**Issue by eamodio** [ryu1kn/vscode-partial-diff#21]
Nothing happens when you try to use the comparison commands in vscode 1.20.

```
[Extension Host] Activating extension `ryu1kn.partial-diff` failed: Invalid or unexpected token. (at Console.originalConsole.(anonymous function) [as error] (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\git\node_modules\diagnostic-channel-publishers\dist\src\console.pub.js:42:39))
t.log @ console.ts:123

[Extension Host] Activating extension `ryu1kn.partial-diff` failed:  Invalid or unexpected token (at Console.originalConsole.(anonymous function) [as error] (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\git\node_modules\diagnostic-channel-publishers\dist\src\console.pub.js:42:39))
t.log @ console.ts:123

[Extension Host] Here is the error stack:  C:\Users\Eric\.vscode-insiders\extensions\ryu1kn.partial-diff-0.5.1\node_modules\clipboardy\lib\macos.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { 
                                                                                                                                                           
SyntaxError: Invalid or unexpected token
	at createScript (vm.js:53:10)
	at Object.runInThisContext (vm.js:95:10)
	at Module._compile (module.js:543:28)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (c:\Program Files\Microsoft VS Code Insiders\resources\app\out\vs\workbench\node\extensionHostProcess.js:664:413)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\git\node_modules\diagnostic-channel\dist\src\patchRequire.js:14:46) (at Console.originalConsole.(anonymous function) [as log] (c:\Program Files\Microsoft VS Code Insiders\resources\app\extensions\git\node_modules\diagnostic-channel-publishers\dist\src\console.pub.js:42:39))
```

**Comment by ryu1kn** [comment]
Hi @eamodio , could you give me more details about how it happened?

I've just updated to v1.20 and did the following and it all seemed to be working fine.

* Select 2 parts of text and compare
* Select nothing and compare entire text
* Compare against clipboard contents

I use macOS v10.13.3

**Comment by eamodio** [comment]
@ryu1kn sorry for the noise -- I uninstalled and re-installed the extension and everything works fine now. The install for my vscode insiders build must have gotten corrupted somehow, while my 1.19 install worked fine.

**Comment by ryu1kn** [comment]
@eamodio Oh I see. No worries! Thanks for confirming it 😉
